### ISSUE TITLE
double "npm" on execution

### ISSUE THREAD

**Issue by ricoli** [bcoe/nyc#225]
So I have an npm script called unit:coverage that goes like this:
```nyc --cache --require babel-core/register --reporter=text-lcov --reporter=lcov --reportDir=test/reports/coverage/unit npm --verbose unit:report```

when running ```npm unit:coverage``` inside a docker container, I'm getting this:
```
npm verb cli [ '/usr/bin/nodejs',
npm verb cli   '/usr/bin/npm',
npm verb cli   '/root/.node-spawn-wrap-13-f4de9a62bba8/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'npm',
npm verb cli   '--verbose',
npm verb cli   'unit:report' ]
npm info using npm@3.3.12
npm info using node@v5.3.0

Usage: npm <command>

where <command> is one of:
   access, add-user, adduser, apihelp, author, bin, bugs, c,
```

As you can see, it's calling ```/usr/bin/nodejs /usr/bin/npm /root/.node-spawn-wrap-13-f4de9a62bba8/node /usr/bin/npm npm --verbose unit:report```. I've tried this on nyc versions 5.6.0 and 6.1.1, same result.

**Comment by bcoe** [comment]
@ricoli can you try `+latest: nyc@6.2.1`. I just released `6.2.1` with some fixes for `Node 5.8.0`.

**Comment by ricoli** [comment]
Just noticed a few seconds before your reply that you published a new version - trying it now :)

**Comment by ricoli** [comment]
Alas, still happens when using version 6.2.1 (spawn-wrap version 1.2.0)

**Comment by bcoe** [comment]
@ricoli could you share a link with a minimal failing example?

@addaleax does anything jump out at you?

**Comment by ricoli** [comment]
Sure, could you please ```docker run ricoli/nyc-debug```?

**Comment by ricoli** [comment]
The dockerfile:
```
FROM ubuntu:14.04

WORKDIR /root/

RUN apt-get update \
  && apt-get install -y wget rlwrap \
  && wget https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/nodejs_5.3.0-1nodesource1~trusty1_amd64.deb \
  && dpkg -i nodejs_5.3.0-1nodesource1~trusty1_amd64.deb \
  && rm nodejs_5.3.0-1nodesource1~trusty1_amd64.deb

ADD package.json /root/
RUN npm install

CMD "npm" "run" "--verbose" "unit:coverage"
```
The package.json:
```
{
  "name": "nyc-debug",
  "scripts": {
    "unit:report": "echo 'unit:report has executed'",
    "unit:coverage": "nyc --cache --reporter=text-lcov --reporter=lcov npm run unit:report"
  },
  "author": "",
  "devDependencies": {
    "nyc": "6.2.1"
  }
}
```

**Comment by addaleax** [comment]
@bcoe I think I already mentioned tapjs/spawn-wrap#19 somewhere around here… anyway, I know the bug and that PR contains the fix for it.

**Comment by ricoli** [comment]
@bcoe I've just tested the newly released spawn-wrap 1.2.1 and indeed it fixes this problem. Since you bundle the dependencies, could you republish to npm with newest spawn-wrap please?

**Comment by ricoli** [comment]
cheeky ping to @bcoe :)

**Comment by bcoe** [comment]
@ricoli hey \o/ give this a shot:

`npm i nyc@next`

If this does the trick I'll promote it to `latest`.

**Comment by ricoli** [comment]
@bcoe just tried v6.3.0 and it worked great :)

**Comment by bcoe** [comment]
@ricoli awesome, should be rolling out the new `nyc` tonight, just working on landing one more feature.

**Comment by bcoe** [comment]
@ricoli this is now released in `6.4.0`.
